---
title: Generator.prototype.throw()
slug: orphaned/Web/JavaScript/Reference/Global_Objects/Generator/throw
tags:
  - ECMAScript 2015
  - Generator
  - JavaScript
  - Method
  - Prototype
  - Reference
translation_of: Web/JavaScript/Reference/Global_Objects/Generator/throw
original_slug: Web/JavaScript/Reference/Global_Objects/Generator/throw
---
<div>{{JSRef}}</div>

<p>Die <code><strong>throw()</strong></code> Methode übergibt dem Generator eine Exception, welche im Generator zu einem Fehler führt. Zudem wird ein Objekt mit den zwei Eigenschaften <code>done</code> und <code>value</code> zurückgegeben.</p>

<h2 id="Syntax">Syntax</h2>

<pre class="syntaxbox"><code><var>gen</var>.throw(exception)</code></pre>

<h3 id="Parameter">Parameter</h3>

<dl>
 <dt><code>exception</code></dt>
 <dd>Die Exception, die geworfen werden soll. Für Debuggingzwecke ist es sinnvoll eine Instanz von {{jsxref("Error")}} zu verwenden.</dd>
</dl>

<h3 id="Rückgabewert">Rückgabewert</h3>

<p>Ein <code><a href="/de/docs/Web/JavaScript/Reference/Global_Objects/Object">Objekt</a></code> mit zwei Eigenschaften:</p>

<ul>
 <li><code>done</code> (boolean)

  <ul>
   <li>Hat den Wert <code>true</code>, wenn der Iterator am Ende der Sequenz angekommen ist. In diesem Fall ist <code>value</code>, der Rückgabewert des Iterators, optional spezifiziert.</li>
   <li>Hat den Wert <code>false</code>, wenn der Iterator einen weiteren Wert aus der Sequenz produzieren kann. Das ist gleichbedeutend damit, dass die <code>done</code> Eigenschaft nicht spezifiziert ist.</li>
  </ul>
 </li>
 <li><code>value</code> - Ein JavaScript Wert, der von einem Iterator zurückgegeben wird. Kann weggelassen werden, wenn <code>done</code> <code>true</code> ist.</li>
</ul>

<h2 id="Beispiele">Beispiele</h2>

<h3 id="Einsatz_von_throw()">Einsatz von <code>throw()</code></h3>

<p>Das folgende Beispiel zeigt einen einfachen Generator und einen Fehler der mit der <code>throw</code> Methode erzeugt wird. Ein Fehler kann mit <code><a href="/de/docs/Web/JavaScript/Reference/Statements/try...catch">try...catch</a></code> abgefangen werden.</p>

<pre class="brush: js">function* gen() {
  while(true) {
    try {
       yield 42;
    } catch(e) {
      console.log('Error caught!');
    }
  }
}

var g = gen();
g.next();
// { value: 42, done: false }
g.throw(new Error('Something went wrong'));
// "Error caught!"
// { value: 42, done: false }
</pre>

<h2 id="Spezifikationen">Spezifikationen</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Spezifikation</th>
   <th scope="col">Status</th>
   <th scope="col">Kommentar</th>
  </tr>
  <tr>
   <td>{{SpecName('ES2015', '#sec-generator.prototype.throw', 'Generator.prototype.throw')}}</td>
   <td>{{Spec2('ES2015')}}</td>
   <td>Initiale Definition.</td>
  </tr>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-generator.prototype.throw', 'Generator.prototype.throw')}}</td>
   <td>{{Spec2('ESDraft')}}</td>
   <td> </td>
  </tr>
 </tbody>
</table>

<h2 id="Browserkompatibilität">Browserkompatibilität</h2>

<div>


<p>{{Compat("javascript.builtins.Generator.throw")}}</p>
</div>

<h2 id="Siehe_auch">Siehe auch</h2>

<ul>
 <li><code><a href="/de/docs/Web/JavaScript/Reference/Statements/function*">function*</a></code></li>
</ul>
