---
title: EvalError
slug: orphaned/Web/JavaScript/Reference/Global_Objects/EvalError
tags:
  - Class
  - EvalError
  - JavaScript
  - Object
  - Reference
translation_of: Web/JavaScript/Reference/Global_Objects/EvalError
original_slug: Web/JavaScript/Reference/Global_Objects/EvalError
---
<div>{{JSRef}}</div>

<p><strong><code>EvalError</code></strong> オブジェクトは、グローバルの {{jsxref("Global_Objects/eval", "eval()")}} 関数に関するエラーを示します。この例外はもう JavaScript からは発生しなくなっていますが、互換性のために <code>EvalError</code> オブジェクトが残っています。</p>

<h2 id="Constructor" name="Constructor">コンストラクター</h2>

<dl>
 <dt>{{jsxref("EvalError/EvalError", "EvalError()")}}</dt>
 <dd>新しい <code>EvalError</code> オブジェクトを生成します。</dd>
</dl>

<h2 id="Instance_properties" name="Instance_properties">インスタンスプロパティ</h2>

<dl>
 <dt>{{jsxref("Error.prototype.message", "EvalError.prototype.message")}}</dt>
 <dd>エラーメッセージです。 ECMA-262 において {{jsxref("EvalError")}} は自身の <code>message</code> プロパティを提供するべきとされていますが、 <a href="/ja/docs/Mozilla/Projects/SpiderMonkey">SpiderMonkey</a> では {{jsxref("Error.prototype.message")}} を継承しています。</dd>
 <dt>{{jsxref("Error.prototype.name", "EvalError.prototype.name")}}</dt>
 <dd>エラー名です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.fileName", "EvalError.prototype.fileName")}}</dt>
 <dd>このエラーが発生したファイルのパスです。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.lineNumber", "EvalError.prototype.lineNumber")}}</dt>
 <dd>このエラーが発生したファイル内の行番号です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.columnNumber", "EvalError.prototype.columnNumber")}}</dt>
 <dd>このエラーが発生した行内の桁番号です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.stack", "EvalError.prototype.stack")}}</dt>
 <dd>スタックトレースです。 {{jsxref("Error")}} から継承しています。</dd>
</dl>

<h2 id="Examples" name="Examples">例</h2>

<p><code>EvalError</code> は現在の ECMAScript 仕様書では使われておらず、このためランタイムからも投げられません。しかしオブジェクト自体は、以前の仕様書との後方互換性のために残っています。</p>

<h3 id="Creating_an_EvalError" name="Creating_an_EvalError">EvalError の生成</h3>

<pre class="brush: js notranslate">try {
  throw new EvalError('Hello', 'someFile.js', 10);
} catch (e) {
  console.log(e instanceof EvalError); // true
  console.log(e.message);              // "Hello"
  console.log(e.name);                 // "EvalError"
  console.log(e.fileName);             // "someFile.js"
  console.log(e.lineNumber);           // 10
  console.log(e.columnNumber);         // 0
  console.log(e.stack);                // "@Scratchpad/2:2:9\n"
}
</pre>

<h2 id="Specifications" name="Specifications">仕様書</h2>

<table class="standard-table">
 <thead>
  <tr>
   <th scope="col">仕様書</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-native-error-types-used-in-this-standard-evalerror', 'EvalError')}}</td>
  </tr>
 </tbody>
</table>

<h2 id="Browser_compatibility" name="Browser_compatibility">ブラウザーの互換性</h2>

<div>
<div class="hidden">このページの互換性一覧表は構造化データから生成されています。データに協力していただけるのであれば、 <a class="external" href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> をチェックアウトしてプルリクエストを送信してください。</div>

<p>{{Compat("javascript.builtins.EvalError")}}</p>
</div>

<h2 id="See_also" name="See_also">関連情報</h2>

<ul>
 <li>{{jsxref("Error")}}</li>
 <li>{{jsxref("Global_Objects/eval", "eval()")}}</li>
</ul>
