---
title: InternalError
slug: orphaned/Web/JavaScript/Reference/Global_Objects/InternalError
tags:
  - Class
  - InternalError
  - JavaScript
  - Object
translation_of: Web/JavaScript/Reference/Global_Objects/InternalError
original_slug: Web/JavaScript/Reference/Global_Objects/InternalError
---
<div>{{JSRef}} {{non-standard_header}}</div>

<p><strong><code>InternalError</code> オブジェクト</strong> は、 JavaScript エンジンで内部的に発生したエラーを示します。</p>

<p>これは、以下のように何かが大きすぎる時に発生します。</p>

<ul>
 <li>"switch case が多すぎる"、</li>
 <li>"正規表現内の括弧が多すぎる"、</li>
 <li>"配列の初期化子が大きすぎる"、</li>
 <li>"再帰が深すぎる"。</li>
</ul>

<h2 id="Constructor" name="Constructor">コンストラクター</h2>

<dl>
 <dt>{{jsxref("InternalError/InternalError", "InternalError()")}}</dt>
 <dd>新しい <code>InternalError</code> オブジェクトを生成します。</dd>
</dl>

<h2 id="Instance_properties" name="Instance_properties">インスタンスプロパティ</h2>

<dl>
 <dt>{{jsxref("Error.prototype.message", "InternalError.prototype.message")}}</dt>
 <dd>エラーメッセージです。 {{jsxref("Error.prototype.message")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.name", "InternalError.prototype.name")}}</dt>
 <dd>エラー名です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.fileName", "InternalError.prototype.fileName")}}</dt>
 <dd>このエラーが発生したファイルのパスです。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.lineNumber", "InternalError.prototype.lineNumber")}}</dt>
 <dd>このエラーが発生したファイル内の行番号です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.columnNumber", "InternalError.prototype.columnNumber")}}</dt>
 <dd>このエラーが発生した行内の桁番号です。 {{jsxref("Error")}} から継承しています。</dd>
 <dt>{{jsxref("Error.prototype.stack", "InternalError.prototype.stack")}}</dt>
 <dd>スタックトレースです。 {{jsxref("Error")}} から継承しています。</dd>
</dl>

<h2 id="Examples" name="Examples">例</h2>

<h3 id="Too_much_recursion" name="Too_much_recursion">深すぎる再帰</h3>

<p>この再帰関数は終了条件によって、10回実行されます。</p>

<pre class="brush: js notranslate">function loop(x) {
  if (x &gt;= 10) // "x &gt;= 10" is the exit condition
    return;
  // do stuff
  loop(x + 1); // the recursive call
}
loop(0);</pre>

<p>この条件を非常に大きな値に設定した場合、動作しなくなります。</p>

<pre class="brush: js example-bad notranslate">function loop(x) {
  if (x &gt;= 1000000000000)
    return;
  // do stuff
  loop(x + 1);
}
loop(0);

// InternalError: too much recursion</pre>

<p>詳しくは、 <a href="/ja/docs/Web/JavaScript/Reference/Errors/Too_much_recursion">InternalError: too much recursion.</a> を参照してください。</p>

<h2 id="Specifications" name="Specifications">仕様書</h2>

<p>仕様の一部ではありません。</p>

<h2 id="Browser_compatibility" name="Browser_compatibility">ブラウザーの互換性</h2>

<div>
<div class="hidden">このページの互換性一覧表は構造化データから生成されています。データに協力していただけるのであれば、 <a class="external" href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> をチェックアウトしてプルリクエストを送信してください。</div>

<p>{{Compat("javascript.builtins.InternalError")}}</p>
</div>

<h2 id="See_also" name="See_also">関連情報</h2>

<ul>
 <li>{{jsxref("Error")}}</li>
 <li>
  <p><a href="/ja/docs/Web/JavaScript/Reference/Errors/Too_much_recursion">InternalError: too much recursion</a></p>
 </li>
</ul>
