---
title: Error.prototype.stack
slug: orphaned/Web/JavaScript/Reference/Global_Objects/Error/Stack
tags:
  - JavaScript
  - 原型
  - 参考
  - 属性
  - 错误
translation_of: Web/JavaScript/Reference/Global_Objects/Error/Stack
original_slug: Web/JavaScript/Reference/Global_Objects/Error/Stack
---
<div>{{JSRef}} {{non-standard_header}}</div>

<p>{{jsxref("Error")}}对象作为一个非标准的栈属性提供了一种函数追踪方式。无论这个函数被被调用，处于什么模式，来自于哪一行或者哪个文件，有着什么样的参数。这个栈产生于最近一次调用最早的那次调用，返回原始的全局作用域调用</p>

<h2 id="描述">描述</h2>

<p>每个步骤都会被分为单独的一行以这个函数的名字作为开始（如果不是一个来自于全局作用域的调用）,然后通过一个@符号标记一个文件的位置（尤其是当一个函数构造错误并且作为错误被抛出，并且如果能定位到这个文件的位置，那么会使用冒号显示行号。（提示）{{jsxref("Error")}}对象在错误跑出时同样能处理并渲染出文件名，行号和列号属性（但是仅仅限于错误。而不是追踪他的路径）</p>

<p>注意这是Firefox定义的格式，并没有标准的定义。但是Safari 6+ 和 Opera 12-定义了一种非常相似的格式。其他使用JavaScript V8引擎的浏览器（例如Chrome, Opera 15+,安卓浏览器）和IE 10+，定义了一种不同的格式（可参见 <a class="external" href="http://msdn.microsoft.com/en-us/library/windows/apps/hh699850.aspx">error.stack</a> 文档）</p>

<p>堆栈中的参数值： Firefox 14版本之前是 ({{bug("744842")}})函数名会随着参数值会在添加@符号之前被立即转换成用圆括号包裹的string类型。然而对象或者数组等其他类型似乎会被转换成<code>"[object Object]"</code>并且这种格式不能回退到之前实际上的对象，而纯值会被渲染（或许这种在Firefox14中仍有这种可能，使用<code>arguments.callee.caller.arguments</code>更加简单。因为函数名可以使用<code>arguments.callee.caller.name</code>渲染）。<code>"undefined"</code>被显示为<code>"(void 0)"</code>不过要注意的是如果是字符串类型的参数会直接以类似<code>"@"</code>, <code>"("</code>, <code>")"</code>格式通过编译（或者是包含在文件名中）。你不能简单的依赖这些将它分成多个组件，但是，对于Firefox14及以后的版本来说，这些都不是问题</p>

<p>不同的浏览器会在不同时期设置这个值。例如，Firefox在创建{{jsxref("Error")}}对象时设置它，然而PhantomJS是在当且仅当它抛出 {{jsxref("Error")}}时， 并且<a href="http://msdn.microsoft.com/en-us/library/windows/apps/hh699850.aspx">MSDN docs</a> 似乎也实现了PhantomJS的方式。</p>

<h2 id="示例">示例</h2>

<p>下面这段html代码展示了<code>stack</code> 属性的使用方法</p>

<pre class="brush: html">&lt;!DOCTYPE HTML&gt;
&lt;meta charset="UTF-8"&gt;
&lt;title&gt;Stack Trace Example&lt;/title&gt;
&lt;body&gt;
&lt;script&gt;
function trace() {
  try {
    throw new Error('myError');
  }
  catch(e) {
    alert(e.stack);
  }
}
function b() {
  trace();
}
function a() {
  b(3, 4, '\n\n', undefined, {});
}
a('first call, firstarg');
&lt;/script&gt;

</pre>

<p>假设上面这段代码被保存在Windows系统下的 <code>C:\example.html</code>在处理过程中抛出如下所示的错误信息</p>

<p>Firefox 30及以上版本的浏览器会包含以列号为开始 ({{bug("762556")}}):</p>

<pre><samp>trace@file:///C:/example.html:9:17
b@file:///C:/example.html:16:13
a@file:///C:/example.html:19:13
@file:///C:/example.html:21:9</samp></pre>

<p>Firefox 14 to Firefox 29:</p>

<pre><samp>trace@file:///C:/example.html:9
b@file:///C:/example.html:16
a@file:///C:/example.html:19
@file:///C:/example.html:21</samp></pre>

<p>Firefox 13及更早版本的浏览器会抛出如下信息：</p>

<pre><samp>Error("myError")@:0
trace()@file:///C:/example.html:9
b(3,4,"\n\n",(void 0),[object Object])@file:///C:/example.html:16
a("first call, firstarg")@file:///C:/example.html:19
@file:///C:/example.html:21</samp></pre>

<h3 id="Stack_of_eval'ed_code">Stack of eval'ed code</h3>

<p>Firefox30以{{geckoRelease("30")}}格式开头，<code>Function()</code> 和 <code>eval()</code> 调用产生的错误代码堆栈，现在在调用内部通过行号和列号以更加详细的格式向我们展示出来。函数调用显示为<code>"&gt; Function"</code> 而 eval调用则是 <code>"&gt; eval"</code>这样。下面来看这个{{bug("332176")}}.</p>

<pre class="brush: js">try {
  new Function('throw new Error()')();
} catch (e) {
  console.log(e.stack);
}

// anonymous@file:///C:/example.html line 7 &gt; Function:1:1
// @file:///C:/example.html:7:6


try {
  eval("eval('FAIL')");
} catch (x) {
  console.log(x.stack);
}

// @file:///C:/example.html line 7 &gt; eval line 1 &gt; eval:1:1
// @file:///C:/example.html line 7 &gt; eval:1:1
// @file:///C:/example.html:7:6
</pre>

<p>你也可以使用<code>//# sourceURL</code> 命名eval源的指令。 也可以查看在 <a href="/en-US/docs/Tools/Debugger">Debugger</a>文档中的<a href="/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources" style="">Debug eval 源</a>和<a href="http://fitzgeraldnick.com/weblog/59/">blog post博客 。</a></p>

<h2 id="规范">规范</h2>

<p>不属于任何规范，没有标准规范。</p>

<h2 id="浏览器兼容性">浏览器兼容性</h2>

<div>
<div>
<div class="hidden">此页面上的兼容性表由数据结构化生成。 如果您想为此做出贡献，请查看<a href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> 并向我们发起拉取请求。</div>

<p>{{Compat("javascript.builtins.Error.stack")}}</p>
</div>
</div>

<h2 id="另请参阅">另请参阅</h2>

<ul>
 <li><a href="/en-US/docs/Components.stack">Components.stack</a></li>
 <li>外部项目: <a class="link-https" href="https://github.com/csnover/TraceKit/">TraceKit</a> and <a class="link-https" href="https://github.com/eriwen/javascript-stacktrace">javascript-stacktrace</a></li>
 <li>MSDN: <a class="external" href="http://msdn.microsoft.com/en-us/library/windows/apps/hh699850.aspx" title="http://msdn.microsoft.com/en-us/library/windows/apps/hh699850.aspx">error.stack</a> docs</li>
 <li><a href="https://github.com/v8/v8/wiki/Stack%20Trace%20API">Overview of the V8 JavaScript stack trace API</a></li>
</ul>
